//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSDNServices
{
    using System;
    using System.Collections.Generic;

    public partial class ThreadsDetail
    {
        public System.Guid Id { get; set; }
        public Nullable<int> ForumID { get; set; }
        public Nullable<int> TeamID { get; set; }
        public Nullable<System.DateTime> ThreadCreateTime { get; set; }
        public Nullable<System.DateTime> FirstReplyTime { get; set; }
        public Nullable<int> IssueTypeID { get; set; }
        public Nullable<int> ReplyNum { get; set; }
        public Nullable<int> TechCategoryID { get; set; }
        public Nullable<bool> IsReplied { get; set; }
        public Nullable<int> CSSAction { get; set; }
        public string Diffcult { get; set; }
        public string CustomerLookingFor { get; set; }
        public Nullable<int> OwnerID { get; set; }
        public Nullable<double> UT { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string ThreadLink { get; set; }
        public string ThreadTitle { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsChanged { get; set; }
        public string Status { get; set; }
        public string Alias { get; set; }
        public Nullable<int> EngineerTeamID { get; set; }
        public string EngnieerTeamName { get; set; }
        public string ForumName { get; set; }
        public string IssueTypeName { get; set; }
        public string TechCategoryName { get; set; }
        public string CSSActionName { get; set; }
        public Nullable<double> Labors { get; set; }
        public string TeamName { get; set; }
        public string IRT { get; set; }
        public string LastReplyUser { get; set; }
    }
}
