//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSDNServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThreadDetail
    {
        public int Id { get; set; }
        public Nullable<System.Guid> ThreadID { get; set; }
        public string ReplyContent { get; set; }
        public string ReplyUserName { get; set; }
        public Nullable<System.DateTime> ReplyTime { get; set; }
        public Nullable<bool> IsAnswer { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> AgreeNumber { get; set; }
        public Nullable<int> DisagreeNumber { get; set; }
        public Nullable<int> SaveNumber { get; set; }
        public Nullable<int> SameNumber { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
    }
}
