//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSDNServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class UT
    {
        public int Id { get; set; }
        public Nullable<System.Guid> ThreadGUID { get; set; }
        public Nullable<double> Labor { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<int> OwnerID { get; set; }
        public string Comments { get; set; }
    
        public virtual Thread Thread { get; set; }
    }
}
