//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSDNServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class UTDetail
    {
        public System.Guid Id { get; set; }
        public Nullable<double> Labor { get; set; }
        public string EngineerName { get; set; }
        public string Alias { get; set; }
        public Nullable<int> EngineerID { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> ThreadCreateTime { get; set; }
    }
}
